title: "Domain Explorers"
remote_theme: pmarsceill/just-the-docs
search_enabled: true
aux_links:
  "Podcast":
    - "https://bettersoftwaredesign.pl"
  "YouTube":
    - "https://www.youtube.com/c/MariuszGil"
aux_links_new_tab: true
footer_content: "Copyright &copy; 2020 Mariusz Gil, Better Software Design."

